jenkins:
    build: ./jenkins
    restart: always
    mem_limit: 4g
    volumes:
      # ssh keys for GitHub and Triton
      # access to the Docker sock to build containers locally
      - /opt/jenkins/.ssh:/var/jenkins_home/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONSUL=localhost
      - DOCKER_TLS_VERIFY=1
    env_file:
      - /opt/jenkins/_jenkins
    net: "host"

# reverse proxy for protecting Jenkins w/ TLS
nginx:
    build: ./nginx
    restart: always
    mem_limit: 128m
    environment:
      - CONSUL=localhost
    env_file:
      - /opt/jenkins/_nginx
    ports:
      - 80:80
      - 443:443
    net: "host"

# local Consul, used for coordinating Nginx only
consul:
    build: ./consul
    restart: always
    mem_limit: 128m
    expose:
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    net: "host"
    command: >
      /usr/local/bin/containerpilot
      /bin/consul agent
        -server
        -bootstrap
        -config-dir=/etc/consul
