jenkins:
    extends:
      file: docker-compose.yml
      service: jenkins
    build: .
    mem_limit: 1g
    environment:
      - CONSUL=consul
    links:
      - consul:consul
    ports:
      - "8000:8000"
      - "2222:22"

consul:
    extends:
      file: docker-compose.yml
      service: consul
    ports:
      - "8500:8500"

nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    build: ./nginx
    environment:
      - CONSUL=consul
      - ACME_ENV=
      - ACME_DOMAIN=
    links:
      - consul:consul
    ports:
      - "8080:80"
      - "4443:443"
      - "9090:9090"
